name = "eko-ciscenje"
compatibility_date = "2026-04-29"
main = "worker/index.js"

[[routes]]
pattern = "eko-ciscenje.lukasulc.com"
custom_domain = true

[[routes]]
pattern = "eko-ciscenje.lukasulc.com"
custom_domain = true

[assets]
directory = "dist"
binding = "ASSETS"

[vars]
CONTACT_TO_EMAIL = "contact@eko-ciscenje.com"
CONTACT_FROM_EMAIL = "no-reply@eko-ciscenje.com"

[[send_email]]
name = "EMAIL"
